#!/usr/bin/env sh

EDITOR=vi

alias ll='ls -l'
alias be='bundle exec'

git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"

